### ISSUE TITLE
/<servername>

### ISSUE THREAD

**Issue by egold555** [egold555/Crotus-Issues#4]

**Comment by egold555** [comment]
This might bypass authme for admins

**Comment by awsomesteve55** [comment]
I will add it to the blocked commands list in MCAuth if it does

**Comment by egold555** [comment]
Wont work, bungee intercepts commands before they reach the server. I might have a way to comunicate between the two

**Comment by awsomesteve55** [comment]
Ok it is not a problem if you can't any ways due to updates in the feature been more then one Factions & Skyblock server

**Comment by egold555** [comment]
Is it do able to add a /hub to the proxy so every server will have /hub (This will connect you to the lobby serer!)
